### ISSUE TITLE
Replace Travis CI with Github Actions

### ISSUE THREAD

**Issue by IanBriggs** [PRUNERS/FLiT#312]
## Feature Request

**Suggested change:**
I would like us to move to github Actions.
In addition I would like to add an OSX instance, since we have compatibility features for OSX.

**Comment by mikebentley15** [comment]
Sure, I'm open to that.  It's nice that you have already tried it out and gotten it to work with your project.

**Benefits of TravisCI**
One of the benefits of TravisCI is that all of the other PRUNERS projects are using it, so there would be consistency and cohesion between the different PRUNERS projects.

However, consistency is not a good enough reason by itself to warrant not moving, else nobody would ever move to better and newer things.

**Question**
Could you comment on the benefits of GitHub Actions over TravisCI?  I believe TravisCI can also handle OSX instances.

**OSX Support**
OSX worked back when I was at LLNL since the computer they gave me was a MAC.  However, since then I have been working on a Linux machine and have not tested MAC.  It would be good to get that working again.

It would take quite a lot of work to add Windows support I think.

**Comment by mikebentley15** [comment]
It looks like TravisCI can be used as one of the GitHub Actions:

https://github.com/travis-ci/actions
